services:
  fctapp:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html
    networks:
      - traefik
    labels:
      - "com.centurylinklabs.watchtower.scope=fctapp"
      # Traefik - Proxy
      - "traefik.enable=true"
      - "traefik.http.routers.fctapp.entryPoints=web, websecure"
      - "traefik.http.routers.fctapp.rule=Host(`fctapp.cacic.dev.br`)"
      - "traefik.http.routers.fctapp.tls=true"
      - "traefik.http.routers.fctapp.tls.certResolver=letsencrypt"
      - "traefik.http.routers.fctapp.tls.domains=fctapp.cacic.dev.br"
      # HTTP Service
      - "traefik.http.routers.fctapp.service=fctapp-svc"
      - "traefik.http.services.fctapp-svc.loadBalancer.server.port=80"
      - "traefik.http.services.fctapp-svc.loadBalancer.passHostHeader=true"

networks:
  traefik:
    external: true
