http:
  middlewares:
    errorpages-mw:
      errors:
        status:
          - "400-401"
          - "403-414"
          - "421"
          - "429"
          - "500-504"
          - "511"
        service: errorpages-svc@docker
        query: "/{status}.html"
