services:
  fctapp:
    image: ghcr.io/cacic-fct/fct-app:main
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - traefik
    labels:
      - "com.centurylinklabs.watchtower.scope=fctapp"
      # Traefik - Proxy
      - "traefik.enable=true"
      # websecure route
      - "traefik.http.routers.fctapp.entryPoints=web, websecure"
      - "traefik.http.routers.fctapp.rule=Host(`fctapp.cacic.dev.br`)"
      - "traefik.http.routers.fctapp.tls=true"
      - "traefik.http.routers.fctapp.tls.certResolver=letsencrypt"
      - "traefik.http.routers.fctapp.tls.domains=fctapp.cacic.dev.br"
      # Middlewares
      - "traefik.http.routers.fctapp.middlewares=fctapp-mw-errors, fctapp-mw-securityheaders"
      ## Errors
      - "traefik.http.middlewares.fctapp-mw-errors.errors.status=400"
      - "traefik.http.middlewares.fctapp-mw-errors.errors.service=fctapp-svc"
      - "traefik.http.middlewares.fctapp-mw-errors.errors.query=/{status}"
      ## Security
      - "traefik.http.middlewares.fctapp-mw-securityheaders.headers.permissionsPolicy=camera=(self), clipboard-read=(self), clipboard-write=(self)"
      ## Privacy
      - "traefik.http.middlewares.fctapp-mw-securityheaders.headers.referrerPolicy=same-origin"
      # HTTP Service
      - "traefik.http.routers.fctapp.service=fctapp-svc"
      - "traefik.http.services.fctapp-svc.loadBalancer.server.port=80"
      - "traefik.http.services.fctapp-svc.loadBalancer.passHostHeader=true"

  fctapp_watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    env_file:
      - secrets.env
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCOPE=fctapp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --http-api-update
    labels:
      - "com.centurylinklabs.watchtower.scope=fctapp"
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.fctapp-watchtower.entryPoints=websecure"
      - "traefik.http.routers.fctapp-watchtower.rule=Host(`watchtower.cacic.dev.br`) && PathPrefix(`/fctapp`)"
      - "traefik.http.routers.fctapp-watchtower.tls=true"
      - "traefik.http.routers.fctapp-watchtower.tls.certResolver=letsencrypt"
      - "traefik.http.routers.fctapp-watchtower.tls.domains=watchtower.cacic.dev.br"
      - "traefik.http.routers.fctapp-watchtower.service=fctapp-watchtower-svc"
      - "traefik.http.services.fctapp-watchtower-svc.loadBalancer.server.port=8080"
      - "traefik.http.routers.fctapp-watchtower.middlewares=fctapp-stripprefix, noindex@file"
      # Remover o prefixo /fctapp para redirecionar o pedido corretamente para a API
      - "traefik.http.middlewares.fctapp-stripprefix.stripprefix.prefixes=/fctapp"

    networks:
      - traefik

networks:
  traefik:
    external: true
